server:
  port: 8085
  servlet:
    context-path: /client
management:
  endpoint:
    health:
      # 端点健康情况，默认值"never"，设置为"always"可以显示硬盘使用情况和线程情况
      show-details: always
  endpoints:
    web:
      exposure:
        # 设置端点暴露的哪些内容，默认["health","info"]，设置"*"代表暴露所有可访问的端点
        include: '*'
spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        # Spring Boot Admin 服务端地址
        url: http://localhost:8084/server
        instance:
          metadata:
            # 客户端端点信息的安全认证信息
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}

  security:
    user:
      name: stodger
      password: qaz1234
logging:
  file:
    name: 'logs/app.log'