server:
  port: 8093
  servlet:
    context-path: /redis
spring:
  redis:
    # 连接地址
    host: localhost
    port: 6379
    password: 123456
    # 连接超时时间（ms）
    timeout: 10000ms
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
      cache:
        # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
        type: redis
logging:
  level:
    com.stodger: debug