server:
  port: 8083
  servlet:
    context-path: /actuator

# 登录账户密码配置
spring:
  security:
    user:
      name: stodger
      password: qaz1234
management:
  # 配置actuator端口
  server:
    port: 9080
    base-path: /sys
  # 端点健康情况，默认值"never"，设置为"always"可以显示硬盘使用情况和线程情况
  endpoint:
    health:
      show-details: always
  # 设置端点暴露的哪些内容，默认["health","info"]，设置"*"代表暴露所有可访问的端点
  endpoints:
    web:
      exposure:
        include: '*'